import AuthProviders from "@/components/providers/AuthProviders";
import "../globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Montserrat } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import UserProfile from "@/components/blog1/UserProfile";
import FollowMe from "@/components/blog1/FollowMe";
import FeaturedPosts from "@/components/blog1/FeaturedPosts";
import Nav from "@/components/blog2/Nav";

const montserrat = Montserrat({
  weight: ["300", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog-App-User-Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body
        className={montserrat.className}
        suppressHydrationWarning={true}
        style={{ overflowY: "scroll", scrollbarColor: "white white", scrollbarWidth: "thin", height: "100vh" }}>
        <AuthProviders>
          <header className="fixed top-0 z-50">
            <Navbar />
          </header>
          <main className="mx-auto mt-24 mb-4 w-full px-4 sm:px-4">
            <div className="grid grid-cols-1 md:grid-cols-12 gap-y-10 md:gap-x-4 lg:gap-x-6">
              <div className="order-1 md:col-span-4 md:order-1 lg:col-span-2 lg:order-1">
                <Nav />
              </div>

              <div className="order-3 md:col-span-12 md:order-3 lg:col-span-7 lg:order-2">{children}</div>

              <div className="order-2 md:col-span-8 md:order-2 lg:col-span-3 lg:order-3 space-y-10">
                <UserProfile />
                <FollowMe />
                <FeaturedPosts />
              </div>
            </div>
          </main>
          <footer>
            <Footer />
          </footer>
        </AuthProviders>
      </body>
    </html>
  );
}
